Bluekey-Payment-System/BPS-BE

.gitignore
Dockerfile
docker-compose.yml
src/main/java/com/github/bluekey/controller/HealthCheckController.java

docker-compose를 통한 container 실행 및 image build

BFS-69/dockerfile, docker compose script와 docker container 실행 여부 결과 확인

---

.github/workflows/deploy.yml
Dockerfile
build.gradle
docker-compose.yml

- Github action script와 docker를 통한 deploy step 개발

BPS-62/github action script와 deploy script

---

src/main/java/com/github/bluekey/controller/member/AuthController.java
src/main/java/com/github/bluekey/dto/JwtInfoDto.java
src/main/java/com/github/bluekey/dto/LoginMemberDto.java
src/main/java/com/github/bluekey/dto/request/LoginRequestDto.java
src/main/java/com/github/bluekey/dto/request/PasswordRequestDto.java
src/main/java/com/github/bluekey/dto/request/SignupRequest.java
src/main/java/com/github/bluekey/dto/request/SignupRequestDto.java
src/main/java/com/github/bluekey/dto/response/LoginTokenResqonseDto.java
src/main/java/com/github/bluekey/dto/response/SignupResponse.java
src/main/java/com/github/bluekey/dto/response/SignupResponseDto.java
src/main/java/com/github/bluekey/entity/member/MemberType.java
src/main/java/com/github/bluekey/exception/ErrorCode.java

- Auth Controller에 Api에 대한 메서드들을 생성했습니다.
- Swagger를 이용해 각 Api에 대한 명세를 작성했습니다.
- 오류 메세지가 다를 경우 어떻게 보여줄지에 대한 고민을 하다가, 우선은 기본 ErrorResponse 구조를 보여줄 수 있도록 설정했습니다.
- MemberType Enum을 추가했으나, 수정이 필요해보입니다.
- reference1

BPS-79/Swagger 명세 - Auth

---

src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/dto/AlbumBaseDto.java
src/main/java/com/github/bluekey/dto/ArtistRevenueProportionDto.java
src/main/java/com/github/bluekey/dto/BestArtistDto.java
src/main/java/com/github/bluekey/dto/CommonDto.java
src/main/java/com/github/bluekey/dto/MemberBaseDto.java
src/main/java/com/github/bluekey/dto/MonthlyRevenueDto.java
src/main/java/com/github/bluekey/dto/TotalAndGrowthDto.java
src/main/java/com/github/bluekey/dto/TrackBaseDto.java
src/main/java/com/github/bluekey/dto/TrackSettlementAmountDto.java
src/main/java/com/github/bluekey/dto/response/ArtistsRevenueProportionReponseDto.java
src/main/java/com/github/bluekey/dto/response/DashboardTotalInfoResponseDto.java
src/main/java/com/github/bluekey/dto/response/MonthlyRevenueTrendResponseDto.java
src/main/java/com/github/bluekey/dto/response/TracksSettlementAmountResponseDto.java

- admin 관련 api swagger 작업했습니다. 
- MemberController에 작성할까 하다가 AdminController를 따로 만들었는데 다른 분들의 생각은 어떤지 궁금합니다.
- Dto 이름이 너무 긴 것 같아 조금 걱정이 되는데 우선은 정보를 다 담을 수 있도록 만들었습니다.
- 증감률이나 비율의 data type을 뭘로 할지 고민이 있었습니다.

BPS-74/Swagger 명세 - Admin

---

src/main/java/com/github/bluekey/controller/transaction/TransactionController.java
src/main/java/com/github/bluekey/dto/response/ListResponse.java
src/main/java/com/github/bluekey/dto/response/transaction/OriginalTransactionPaginationResponseDto.java
src/main/java/com/github/bluekey/dto/response/transaction/OriginalTransactionResponseDto.java
src/main/java/com/github/bluekey/entity/transaction/OriginalTransaction.java
src/main/java/com/github/bluekey/entity/transaction/Transaction.java
src/main/java/com/github/bluekey/repository/transaction/OriginalTransactionRepository.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java
src/main/resources/application-local.yml

- OriginalTransaction swagger 문서 작업

BPS-77/transaction domain swagger API 명세 작업

---

src/main/java/com/github/bluekey/entity/transaction/OriginalTransaction.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/exception/transaction/TransactionAlreadyUploadException.java

`OriginalTransaction` entity class 작업

BPS-85/OriginalTransaction entity 설계

---

src/main/java/com/github/bluekey/entity/album/Album.java
src/main/java/com/github/bluekey/repository/album/AlbumRepository.java

BPS-111/Album entity 설계

---

src/main/java/com/github/bluekey/entity/album/Album.java
src/main/java/com/github/bluekey/entity/track/Track.java
src/main/java/com/github/bluekey/entity/track/TrackMember.java
src/main/java/com/github/bluekey/entity/transaction/OriginalTransaction.java
src/main/java/com/github/bluekey/entity/transaction/Transaction.java
src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
src/main/java/com/github/bluekey/repository/track/TrackRepository.java

Track, TrackMember entity 설계와 연관관계 매핑

BPS-125/ Track, TrackMember entity

---

src/main/resources/application-local.yml
src/main/resources/sql/data.sql

table에 들어갈 dump용 데이터 Insert SQL문 작성

BPS-134/dump용 data.sql 

---

src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
src/main/java/com/github/bluekey/repository/member/MemberRepository.java
src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java

유통사에서 제공하는 엑셀파일에서 공통적으로 수행이 되는 Validation check method 정의

BPS-135/ DBPersistenceValidator 정의

---

src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/dto/AlbumBaseDto.java
src/main/java/com/github/bluekey/dto/AlbumInfoDto.java
src/main/java/com/github/bluekey/dto/AlbumMonthlyInfoDto.java
src/main/java/com/github/bluekey/dto/AlbumMonthlyTrackInfoDto.java
src/main/java/com/github/bluekey/dto/AlbumTopDto.java
src/main/java/com/github/bluekey/dto/AlbumTrackAccontsDto.java
src/main/java/com/github/bluekey/dto/ArtistInfoDto.java
src/main/java/com/github/bluekey/dto/ArtistMonthlyAlbumDto.java
src/main/java/com/github/bluekey/dto/ArtistMonthlyArtistsDto.java
src/main/java/com/github/bluekey/dto/ArtistMonthlyInfoDto.java
src/main/java/com/github/bluekey/dto/ArtistMonthlySettlementInfoDto.java
src/main/java/com/github/bluekey/dto/ArtistMonthlyTrackDto.java
src/main/java/com/github/bluekey/dto/ArtistMonthlyTrackInfoDto.java
src/main/java/com/github/bluekey/dto/ArtistMonthlyTrackListDto.java
src/main/java/com/github/bluekey/dto/ArtistProfileListDto.java
src/main/java/com/github/bluekey/dto/TrackInfoListDto.java
src/main/java/com/github/bluekey/dto/request/AdminArtistProfileRequestDto.java
src/main/java/com/github/bluekey/dto/request/AlbumsRequestDto.java
src/main/java/com/github/bluekey/dto/request/ArtistRequestDto.java
src/main/java/com/github/bluekey/dto/request/TrackRequestDto.java
src/main/java/com/github/bluekey/dto/response/AdminArtistProfileListReponseDto.java
src/main/java/com/github/bluekey/dto/response/AlbumListReponseDto.java
src/main/java/com/github/bluekey/dto/response/AlbumTrackListReponseDto.java
src/main/java/com/github/bluekey/dto/response/ArtistAlbumsListReponseDto.java
src/main/java/com/github/bluekey/dto/response/ArtistListReponseDto.java
src/main/java/com/github/bluekey/dto/response/ArtistMonthlyTrackListReponseDto.java
src/main/java/com/github/bluekey/dto/response/ArtistTopReponseDto.java
src/main/java/com/github/bluekey/dto/response/TrackResponseDto.java

dto class에 대해 invalid field naming 수정과 swagger 문서 추가

BPS-116/Swagger API

---

src/main/java/com/github/bluekey/BluekeyApplication.java
src/main/java/com/github/bluekey/controller/member/AuthController.java
src/main/java/com/github/bluekey/dto/request/SignupRequestDto.java
src/main/java/com/github/bluekey/dto/response/SignupResponseDto.java
src/main/java/com/github/bluekey/entity/member/Email.java
src/main/java/com/github/bluekey/entity/member/Member.java
src/main/java/com/github/bluekey/entity/member/Password.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/repository/member/MemberRepository.java
src/main/java/com/github/bluekey/service/member/MemberService.java

- admin 회원가입 메서드 구현
- TODO: Validation 및 Exception에 대한 구체화
LoginId 값 자체는 유니크 해야하므로 모든 member에 대해 검사
Email은 각 타입끼리 비교할 수 있도록 메서드 구성
타입별로 name, enName 검색 가능하도록 메서드 구성
- reference1

BPS-108/admin 회원가입 api 구현

---

src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
src/main/java/com/github/bluekey/processor/NameExtractor.java
src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
src/main/java/com/github/bluekey/repository/track/TrackRepository.java
src/main/resources/sql/data.sql

아통 유통사의 정산내역 엑셀 파일을 기준으로 DB에 실제 존재하는 데이터인지에 대한 비교와 validation logic 개발

BPS-139/ 아토 유통사 엑셀 파일에 대해 DB 데이터 비교 validation

---

src/main/java/com/github/bluekey/controller/member/MemberController.java
src/main/java/com/github/bluekey/dto/AdminAccountDto.java
src/main/java/com/github/bluekey/dto/ArtistAccountDto.java
src/main/java/com/github/bluekey/dto/response/AdminAccountResponseDto.java
src/main/java/com/github/bluekey/dto/response/AdminAndArtistAccountResponseDto.java
src/main/java/com/github/bluekey/dto/response/ArtistAccountResponseDto.java

- 멤버들의 계정 리스트를 반환하는 api에 대해 명세
- reference1

BPS-145/계정 리스트 반환 api 명세

---

src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
src/main/java/com/github/bluekey/s3/manager/AwsS3Manager.java
src/main/java/com/github/bluekey/s3/manager/ResourceManager.java
src/main/java/com/github/bluekey/s3/manager/S3PrefixType.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java
src/main/resources/application-local.yml
src/main/resources/sql/data.sql

Validation check logic이 끝나 문제가 없는 excel file에 대해서 S3에 업로드 하는 로직 개발

BPS-150/Valid excel file upload

---

src/main/java/com/github/bluekey/config/JpaAuditingConfig.java
src/main/java/com/github/bluekey/dto/request/SignupRequestDto.java
src/main/java/com/github/bluekey/entity/BaseTimeEntity.java
src/main/java/com/github/bluekey/entity/album/Album.java
src/main/java/com/github/bluekey/entity/member/Password.java
src/main/java/com/github/bluekey/entity/track/Track.java
src/main/java/com/github/bluekey/entity/track/TrackMember.java
src/main/java/com/github/bluekey/entity/transaction/OriginalTransaction.java
src/main/java/com/github/bluekey/entity/transaction/Transaction.java
src/main/java/com/github/bluekey/service/member/MemberService.java
src/main/resources/sql/data.sql

BaseTimeEntity 구현과 각 Entity class에 상속 적용

Feature/BaseTimeEntity 설계

---

src/main/java/com/github/bluekey/controller/member/AuthController.java
src/main/java/com/github/bluekey/dto/request/PasswordRequestDto.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/exception/member/MemberException.java
src/main/java/com/github/bluekey/exception/member/MemberNotFoundException.java
src/main/java/com/github/bluekey/service/auth/AuthService.java
src/main/java/com/github/bluekey/service/member/MemberService.java

- password 관련 api를 구현했습니다.
- reference1

BPS-152/password 관련 api 구현

---

src/main/java/com/github/bluekey/config/SecurityConfig.java
src/main/java/com/github/bluekey/controller/member/AuthController.java
src/main/java/com/github/bluekey/entity/BaseTimeEntity.java
src/main/java/com/github/bluekey/entity/member/Member.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/service/auth/AuthService.java

- 슈퍼 어드민이 계정을 삭제하는 API 개발
TODO: api마다 접근 권한 설정 필요

BPS-154/슈퍼 어드민이 계정을 삭제하는 API 개발

---

src/main/java/com/github/bluekey/config/SecurityConfig.java
src/main/java/com/github/bluekey/controller/transaction/TransactionController.java
src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
src/main/java/com/github/bluekey/processor/ProcessManager.java
src/main/java/com/github/bluekey/repository/transaction/OriginalTransactionRepository.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java

`OriginalTransaction` table의 데이터를 기반으로 S3 Object를 가져와 Workbook type으로 가공하는 로직 추가

BPS-157/S3 object processor

---

src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/dto/artist/ArtistAccountDto.java
src/main/java/com/github/bluekey/entity/member/Member.java
src/main/java/com/github/bluekey/service/member/MemberService.java

- admin이 artist의 profile을 변경하는 api 구현
- 메서드 접근 권한 설정

BPS-168/admin이 artist의 profile을 변경하는 api 구현

---

src/main/java/com/github/bluekey/jwt/JwtProvider.java
src/main/java/com/github/bluekey/service/member/MemberService.java

fix: 로직 수정

---

src/main/java/com/github/bluekey/controller/member/AuthController.java
src/main/java/com/github/bluekey/dto/auth/LoginAdminDto.java
src/main/java/com/github/bluekey/dto/auth/LoginMemberDto.java
src/main/java/com/github/bluekey/dto/response/auth/AdminLoginTokenResponseDto.java
src/main/java/com/github/bluekey/entity/member/Member.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/service/auth/AuthService.java

- 멤버 로그인과 어드민 로그인을 분리했습니다.
- 각 타입에 따라 Response를 분리했습니다.
- reference1

BPS-204/login 관련 기능 수정

---

src/main/java/com/github/bluekey/config/SecurityConfig.java

bugfix: cors 설정

---

src/main/java/com/github/bluekey/config/SwaggerConfig.java

- swagger url 설정 추가
- reference1

feat: swagger Url 설정 추가

---

src/main/java/com/github/bluekey/config/SecurityConfig.java

- 스웨거에서 테스트 할 수 있도록 spring security 설정
- reference1

fix: swagger 접근 권한 설정

---

src/main/java/com/github/bluekey/config/SwaggerConfig.java

- Swagger jwt 인증 추가
- reference1

docs: swagger 인증 추가

---

src/main/java/com/github/bluekey/config/SwaggerConfig.java

- 모든 api에서 전역으로 jwt 토큰을 사용할 수 있도록 수정했습니다.
- reference1

fix: swagger 인증 수정

---

src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/controller/member/MemberController.java
src/main/java/com/github/bluekey/dto/admin/AdminAccountDto.java
src/main/java/com/github/bluekey/dto/response/artist/ArtistProfileResponseDto.java
src/main/java/com/github/bluekey/repository/member/MemberRepository.java
src/main/java/com/github/bluekey/service/member/MemberService.java

- 어드민 계정 목록 확인 (페이지네이션) > Super_admin 권한
- 아티스트 계정 목록 확인 (페이지네이션) > super admin, admin 권한
- reference1

BPS-210/admin-artist 계정 관리를 위한 API 구현

---

src/main/java/com/github/bluekey/controller/track/TrackController.java
src/main/java/com/github/bluekey/dto/request/track/TrackRequestDto.java
src/main/java/com/github/bluekey/dto/response/track/TrackResponseDto.java
src/main/java/com/github/bluekey/entity/track/Track.java
src/main/java/com/github/bluekey/service/track/TrackService.java

feat: track 기본 API 구현

---

src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
src/main/java/com/github/bluekey/processor/provider/MafiaDistributorExcelFileProvider.java
src/main/java/com/github/bluekey/processor/type/MafiaExcelColumnType.java
src/main/java/com/github/bluekey/processor/type/MusicDistributorType.java
src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
src/main/java/com/github/bluekey/processor/validator/DistributorExcelValidator.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java
src/main/resources/sql/data.sql

마피아 유통사 엑셀파일 기준 validation 체크 및 upload시에 DB에 migration 하는 로직 추가

BPS-190/Mafia-validation

---

src/main/java/com/github/bluekey/controller/track/TrackController.java
src/main/java/com/github/bluekey/dto/request/track/TrackRequestDto.java
src/main/java/com/github/bluekey/dto/response/track/TrackResponseDto.java
src/main/java/com/github/bluekey/dto/track/TrackCommissionRateDto.java
src/main/java/com/github/bluekey/entity/track/TrackMember.java
src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
src/main/java/com/github/bluekey/service/track/TrackService.java
src/main/resources/application-local.yml

Track 생성 API 기능 추가와 RequestDto, ResponseDto 수정
```json
{
"trackId": 45,
"albumId": 1,
"name": "내 마음 모르죠2",
"enName": "Can you read my heart2",
"isOriginalTrack": true,
"artists": [
{
"memberId": 1,
"name": "실제 pk가 1인 아티스트 이름",
"commissionRate": 30
},
{
"memberId": null,
"name": "김여름",
"commissionRate": 0
}
]
}
```

BPS-216/Track 생성 API

---

src/main/java/com/github/bluekey/controller/track/TrackController.java
src/main/java/com/github/bluekey/service/track/TrackService.java

- 트랙 삭제 API Url 변경과 soft delete 방식으로 변경

BPS-217/Track 삭제 API 수정

---

src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/exception/transaction/AlreadyOriginalTransactionExistException.java
src/main/java/com/github/bluekey/repository/transaction/OriginalTransactionRepository.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java

- `YYYY-MM`  형식에 맞는 엑셀파일 리스트 조회 API

BPS223/업로드된 엑셀파일 조회 API

---

src/main/java/com/github/bluekey/service/transaction/TransactionService.java
src/main/java/com/github/bluekey/util/ExcelUploadUtil.java

BPS-224/엑셀 파일 삭제 API

---

src/main/java/com/github/bluekey/service/transaction/TransactionService.java

…rue 처리 추가
- OriginalTransaction이 삭제될 경우 Transactions 들에 대해서 `isRemoved=true` 처리 적용

hotfix/OriginalTransaction 삭제 event

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/dto/response/album/AlbumResponseDto.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/repository/member/MemberRepository.java
src/main/java/com/github/bluekey/service/album/AlbumService.java
src/main/java/com/github/bluekey/util/ImageUploadUtil.java

BPS-225/앨범 생성

---

src/main/java/com/github/bluekey/config/SecurityConfig.java
src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
src/main/java/com/github/bluekey/jwt/JwtAuthenticationFilter.java
src/main/java/com/github/bluekey/service/member/MemberService.java

…or response handle 로직 추가
- static 페이지에서 admin에 대한 접근만 가능한지 판별하는 API 추가

BPS-228/admin-check api

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
src/main/java/com/github/bluekey/repository/track/TrackRepository.java
src/main/java/com/github/bluekey/service/album/AlbumService.java
src/main/java/com/github/bluekey/service/auth/AuthService.java
src/main/resources/sql/data.sql

BPS-226/앨범 삭제 API 구현

---

src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
src/main/java/com/github/bluekey/jwt/JwtAuthenticationFilter.java

- exception handler 수정
- reference1

fix: security exception 수정

---

src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/dto/artist/ArtistProfileViewDto.java
src/main/java/com/github/bluekey/jwt/JwtAuthenticationFilter.java
src/main/java/com/github/bluekey/service/member/MemberService.java

- 로그인한 아티스트 프로필 조회(본인 프로필 조회) API 구현
- reference1

Bps 163/feature/get artist profile

---

src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/dto/admin/AdminProfileViewDto.java
src/main/java/com/github/bluekey/service/member/MemberService.java

- 로그인한 어드민 프로필 가져오기
- reference1

BPS-231/admin 프로필 가져오기 API

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/dto/artist/ArtistInfoDto.java
src/main/java/com/github/bluekey/dto/response/album/AlbumTrackListResponseDto.java
src/main/java/com/github/bluekey/dto/track/TrackArtistsDto.java
src/main/java/com/github/bluekey/dto/track/TrackInfoListDto.java
src/main/java/com/github/bluekey/repository/track/TrackRepository.java
src/main/java/com/github/bluekey/service/album/AlbumService.java

- 앨범 정보 조회 api 생성
- reference1

BPS-209/앨범 정보 조회

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/dto/artist/ArtistRevenueProportionDto.java
src/main/java/com/github/bluekey/dto/response/artist/ArtistsRevenueProportionResponseDto.java
src/main/java/com/github/bluekey/repository/transaction/TransactionRepository.java
src/main/java/com/github/bluekey/service/dashboard/DashBoardService.java
src/main/resources/sql/data.sql

rank 수에 따라 Donut chart에서 사용하는 Top Artist list 조회 API 개발
```json
{
"contents": [
{
"artist": {
"memberId": 1,
"name": "혁기",
"enName": "hucki"
},
"revenue": 53272.0,
"growthRate": 173.0,
"proportion": 85.0
},
{
"artist": {
"memberId": 5,
"name": "SKY",
"enName": "SKY"
},
"revenue": 6223.0,
"growthRate": -12.0,
"proportion": 10.0
},
{
"artist": {
"memberId": 7,
"name": "송민섭",
"enName": "송민섭"
},
"revenue": 1490.0,
"growthRate": null,
"proportion": 2.0
},
{
"artist": {
"memberId": 2,
"name": "53X",
"enName": "53X"
},
"revenue": 474.0,
"growthRate": null,
"proportion": 0.7
},
{
"artist": null,
"revenue": 656.0,
"growthRate": null,
"proportion": 2.2
}
]
}
```

BPS-230/admin dashboard의 donut chart API 

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/dto/album/AlbumTopDto.java
src/main/java/com/github/bluekey/dto/response/album/AlbumTopResponseDto.java
src/main/java/com/github/bluekey/service/dashboard/DashBoardService.java

album 상세에서 Rank 수에 따른 Top Track list 조회 API 개발
```json
{
"contents": [
{
"track": {
"trackId": 1,
"name": "그대 안아줄게요",
"enName": "그대 안아줄게요"
},
"revenue": 4051.0,
"growthRate": null,
"proportion": 65.0
},
{
"track": {
"trackId": 12,
"name": "그대 안아줄게요 (Acoustic ver.)",
"enName": "그대 안아줄게요 (Acoustic ver.)"
},
"revenue": 1868.0,
"growthRate": null,
"proportion": 30.0
},
{
"track": {
"trackId": 11,
"name": "내 마음 모르죠",
"enName": "mind"
},
"revenue": 238.0,
"growthRate": null,
"proportion": 3.0
},
{
"track": null,
"revenue": 23.0,
"growthRate": null,
"proportion": 2.0
}
]
}
```

BPS-232/album donut API

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/service/dashboard/TopTrackDashBoardService.java

아티스트의 YYYY-MM 기준 정산액이 많은 Top track 리스트 조회 API 개발

BPS-233/아티스트 기준 Top tracks 조회 API

---

src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/dto/response/common/DashboardTotalInfoResponseDto.java
src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java

Admin의 대시보드화면에서 사용되는 summary에 대한 데이터 조회 API 개발
```json
{
"revenue": {
"totalAmount": 62380,
"growthRate": 128.0
},
"newIncome": {
"totalAmount": 60322,
"growthRate": 128.0
},
"settlementAmount": {
"totalAmount": 41997,
"growthRate": 119.0
},
"bestArtist": {
"memberId": 1,
"name": "혁기",
"enName": "hucki",
"growthRate": 173.0
}
}
```

BPS-234/admin dashboard summary

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/dto/response/album/AlbumSummaryResponseDto.java
src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java

앨범 상세 뷰에서 사용되는 앨범에 대한 기본정보와 summary에 대한 데이터를 반환하는 API
```json
{
"name": "미녀 OST",
"enName": "미녀 OST",
"revenue": {
"totalAmount": 18444,
"growthRate": 2.8
},
"newIncome": {
"totalAmount": 17836,
"growthRate": 2.8
},
"settlementAmount": {
"totalAmount": 12911,
"growthRate": 2.8
},
"bestTrack": {
"trackId": 20,
"name": "고백이야",
"enName": "고백이야",
"growthRate": 67.0
}
}
```
```json
{
"name": "미녀 OST",
"enName": "미녀 OST",
"revenue": null,
"newIncome": null,
"settlementAmount": {
"totalAmount": 54,
"growthRate": -31.0
},
"bestTrack": {
"trackId": 18,
"name": "내 세상은",
"enName": "내 세상은",
"growthRate": -31.0
}
}
```

BPS-235/Album summary API

---

src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/dto/response/artist/ArtistSummaryResponseDto.java
src/main/java/com/github/bluekey/entity/transaction/Transaction.java
src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java

Artist dashboard summary 조회 API 개발과 `Transaction` table indexing 추가
```json
{
"settlementAmount": {
"totalAmount": 108.15008030999999,
"growthRate": 178.0
},
"bestAlbum": {
"albumId": 8,
"name": "미녀 OST",
"enName": "미녀 OST",
"growthRate": 178.0
},
"bestTrack": {
"trackId": 18,
"name": "내 세상은",
"enName": "내 세상은",
"growthRate": 178.0
}
}
```

BPS-237/Artist dashboard summary 조회 API

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/dto/album/AlbumMonthlyAccountsDto.java
src/main/java/com/github/bluekey/repository/transaction/TransactionRepository.java
src/main/java/com/github/bluekey/service/dashboard/BarChartDashboard.java
src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java

- 앨범 bar chart 조회 api 구현
```JSON
{
"contents": [
{
"month": 7,
"settlement": null,
"revenue": 8970.624403779026,
"netIncome": 6279.437082645318
},
{
"month": 8,
"settlement": null,
"revenue": 36889.40860834536,
"netIncome": 25822.586025841752
}
]
}
```
어드민이 조회한 경우
```JSON
{
"contents": [
{
"month": 7,
"settlement": 1947.76843709151,
"revenue": 6492.5614569717,
"netIncome": null
},
{
"month": 8,
"settlement": 9091.66454720478,
"revenue": 30305.548490682602,
"netIncome": null
}
]
}
```
아티스트가 조회한 경우
- reference1

BPS-239/album bar chart 조회 API 구현

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/dto/album/AlbumTrackMonthlyTrendInfoDto.java
src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
src/main/java/com/github/bluekey/service/dashboard/LineChartDashBoardService.java

- 트랙별 추이 조회 API 구현
```JSON
{
"tracks": [
{
"trackId": 18,
"name": "익명의트랙1",
"enName": "익명의트랙1",
"monthlyTrend": [
{
"month": 7,
"settlement": null,
"revenue": 129.36381115
},
{
"month": 8,
"settlement": null,
"revenue": 360.5002677
}
]
},
{
"trackId": 19,
"name": "익명의트랙2",
"enName": "익명의트랙2",
"monthlyTrend": [
{
"month": 7,
"settlement": null,
"revenue": 2348.6991356573253
},
{
"month": 8,
"settlement": null,
"revenue": 6223.359849962759
}
]
},
{
"trackId": 20,
"name": "익명의트랙3",
"enName": "익명의트랙3",
"monthlyTrend": [
{
"month": 7,
"settlement": null,
"revenue": 3264.1710199999998
},
{
"month": 8,
"settlement": null,
"revenue": 21917.891754826982
}
]
},
{
"trackId": 21,
"name": "익명의트랙4",
"enName": "익명의트랙4",
"monthlyTrend": [
{
"month": 7,
"settlement": null,
"revenue": 3228.3904369717
},
{ …
```

BPS-244/트랙별 추이 조회 API 구현

---

src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/dto/common/MemberBaseDto.java
src/main/java/com/github/bluekey/dto/response/track/TracksSettlementAmountResponseDto.java
src/main/java/com/github/bluekey/dto/track/TrackSettlementAmountDto.java
src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java

- 어드민 대시보드 화면에서 사용되는 월별 트랙 페이지네이션 API 추가
```json
{
"totalItems": 24,
"contents": [
{
"track": {
"trackId": 20,
"name": "고백이야",
"enName": "고백이야"
},
"album": {
"albumId": 8,
"name": "미녀 OST",
"enName": "미녀 OST"
},
"artists": [
{
"memberId": 1,
"name": "혁기",
"enName": "hucki"
}
],
"revenue": 10959,
"newIncome": 10598,
"settlementAmount": 7418,
"commissionRate": 70
},
{
"track": {
"trackId": 21,
"name": "비밀스럽게",
"enName": "비밀스럽게"
},
"album": {
"albumId": 8,
"name": "미녀 OST",
"enName": "미녀 OST"
},
"artists": [
{
"memberId": 1,
"name": "혁기",
"enName": "hucki"
}
],
"revenue": 4194,
"newIncome": 4056,
"settlementAmount": 2839,
"commissionRate": 70
},
{
"track": {
"trackId": 19,
"name": "Wait For You",
"enName": "Wait For You"
},
"album": {
"albumId": 8,
"name": "미녀 OST",
"enName": "미녀 OST"
}, …
```

BPS-240/월별 트랙 페이지네이션 API

---

src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/dto/artist/ArtistMonthlyArtistsDto.java
src/main/java/com/github/bluekey/dto/artist/ArtistMonthlyTrackListDto.java
src/main/java/com/github/bluekey/dto/response/artist/ArtistMonthlyTrackListResponseDto.java
src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java

- 아티스트 대시보드 뷰에서의 이 달의 track list 반환 API

BPS-246/artist track monthly API

---

src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/controller/transaction/TransactionController.java
src/main/java/com/github/bluekey/dto/request/transaction/OriginalTransactionRequestDto.java
src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
src/main/java/com/github/bluekey/service/dashboard/LineChartDashBoardService.java
src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java
src/main/java/com/github/bluekey/service/dashboard/TopTrackDashBoardService.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java

feat: monthly format 변경

---

.gitignore
build.gradle
src/main/java/com/github/bluekey/mail/EmailSender.java
src/main/resources/application-local.yml

BPS-206/mail 메서드 구현

---

src/main/java/com/github/bluekey/service/transaction/TransactionService.java

- 파일 업로드 시 메일 전송 로직 추가
- reference1

BPS-255/파일 업로드 시 메일 전송 로직 추가

---

src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/dto/admin/AdminArtistProfileListDto.java
src/main/java/com/github/bluekey/dto/response/admin/AdminArtistProfileListReponseDto.java
src/main/java/com/github/bluekey/repository/member/MemberRepository.java
src/main/java/com/github/bluekey/service/dashboard/TopTrackDashBoardService.java
src/main/java/com/github/bluekey/service/member/MemberService.java

관리자가 아티스트의 현황을 확인할 수 있는 pagination API
```json
{
"totalItems": 7,
"contents": [
{
"artist": {
"memberId": 1,
"name": "혁기",
"enName": "hucki",
"profileImage": "image/profile/artist.jpg"
},
"revenue": 6492,
"netIncome": 1947,
"settlementAmount": 1883,
"representativeTrack": "고백이야",
"monthlyIncreaseRate": null
},
{
"artist": {
"memberId": 2,
"name": "53X",
"enName": "53X",
"profileImage": "image/profile/artist.jpg"
},
"revenue": 0,
"netIncome": 0,
"settlementAmount": 0,
"representativeTrack": "",
"monthlyIncreaseRate": null
},
{
"artist": {
"memberId": 3,
"name": "덤프",
"enName": "dump",
"profileImage": "image/profile/artist.jpg"
},
"revenue": 0,
"netIncome": 0,
"settlementAmount": 0,
"representativeTrack": "",
"monthlyIncreaseRate": null
},
{
"artist": {
"memberId": 4,
"name": "이은성", …
```

BPS-256/아티스트 현황 조회 API

---

src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java

fix: bar 차트 수정

---

build.gradle
src/main/java/com/github/bluekey/controller/SentryCheckController.java

BPS-279/sentry integration

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/dto/response/album/AlbumResponseDto.java
src/main/java/com/github/bluekey/service/album/AlbumService.java

- 앨범 수정 API 구현
- `file` 필드가 `null`로 오면 프로필 사진을 수정하지 않도록 구현
- 앨범 사진 삭제 api 구현 필요 
- reference1

BPS-264(BPS-291)/앨범 수정 API 구현

---

src/main/java/com/github/bluekey/util/DashboardUtil.java

- dashboard 리팩토링 작업 전 공통 메서드를 분리하였습니다.
- reference1

BPS-281/dashboard 공통 사용 method 분리

---

src/main/java/com/github/bluekey/exception/transaction/ExcelUploadException.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java

파일 업로드 API 호출 시에 엑셀파일 데이터 validation의 문제 발생시 400 response를 반환할 경우 엑셀파일명도 반환할 수 있도록 response format 변경

BPS-309/transaction response format 변경

---

src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
src/main/resources/application-local.yml

- max size 설정
- file size exception 핸들링
- reference1

BPS-269 (+BPS-270)/file size 설정

---

src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/service/member/MemberService.java

- 아티스트는 다른 아티스트의 대시보드의 값을 받아올 수 없도록 수정
- reference1

BPS-308/아티스트는 다른 아티스트의 대시보드의 값을 받아올 수 없도록 수정

---

src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java

Transaction Service 쪽의 exception에 대한 정의와 반환 로직 추가

BPS-288/Transcation exception 정의

---

src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/repository/member/MemberRepository.java
src/main/java/com/github/bluekey/repository/transaction/OriginalTransactionRepository.java
src/main/java/com/github/bluekey/service/auth/AuthService.java
src/main/java/com/github/bluekey/service/auth/CustomUserDetailsService.java
src/main/java/com/github/bluekey/service/member/MemberService.java

BPS-284/member exception 정의

---

build.gradle
src/main/java/com/github/bluekey/config/security/SecurityConfig.java
src/main/java/com/github/bluekey/config/security/jwt/JWTAuthenticationEntryPoint.java
src/main/java/com/github/bluekey/config/security/jwt/JwtAuthenticationFilter.java
src/main/java/com/github/bluekey/config/security/jwt/JwtProvider.java
src/main/java/com/github/bluekey/config/security/jwt/JwtValidationType.java
src/main/java/com/github/bluekey/config/security/jwt/PrincipalConvertUtil.java
src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/controller/member/AuthController.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
src/main/java/com/github/bluekey/exception/UploadErrorResponse.java
src/main/java/com/github/bluekey/service/auth/AuthService.java

JWT가 Invalid한 경우에 대해 exception case 정리와 response 반환 로직 개선
```java
try {
getClaims(token.substring(BEARER_TOKEN_PREFIX));
return JwtValidationType.VALID_JWT;
} catch (IllegalArgumentException e) {
return JwtValidationType.EMPTY_JWT;
} catch (MalformedJwtException e) {
return JwtValidationType.INVALID_JWT;
} catch (ExpiredJwtException e) {
return JwtValidationType.EXPIRED_JWT;
} catch (UnsupportedJwtException e) {
return JwtValidationType.UNSUPPORTED_JWT;
} catch (SignatureException e) {
return JwtValidationType.INVALID_JWT_SIGNATURE;
}
```

BPS-317/JWT validation

---

src/main/java/com/github/bluekey/repository/member/MemberRepository.java
src/main/java/com/github/bluekey/service/album/AlbumService.java

- Album Service exception refactoring

BPS-285/album exception refactoring

---

src/main/java/com/github/bluekey/controller/member/AdminController.java
src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/dto/filter/MonthlyTrackFilter.java
src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java

- 대시 보드 트랙 페이지네이션 뷰에서 filtering과 soring 기능 추가

BPS-313/dashboard monthly tracks filtering, sorting

---

src/main/java/com/github/bluekey/controller/member/ArtistController.java
src/main/java/com/github/bluekey/service/member/MemberService.java

- 프로필 이미지를 삭제할 수 있는 api를 추가하였습니다.
- reference1

BPS-298/유저 프로필 이미지 삭제 api 추가

---

src/main/java/com/github/bluekey/controller/album/AlbumController.java
src/main/java/com/github/bluekey/service/album/AlbumService.java
src/main/resources/application-local.yml

- 앨범 이미지 삭제를 위한 api를 구현했습니다.
- 
- reference1

BPS-297/앨범 이미지 삭제 api 구현

---

src/main/java/com/github/bluekey/dto/admin/AdminProfileViewDto.java
src/main/java/com/github/bluekey/dto/artist/ArtistProfileViewDto.java

- 로그인 api에서 반환해주던 정보를 별도의 api를 통해 반환받을 수 있도록 수정
- reference1

BPS-311/refactor 로그인과 유저 정보 반환 api 분리를 위한 코드 수정

---

src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
src/main/java/com/github/bluekey/processor/provider/MafiaDistributorExcelFileProvider.java
src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java

- 마피아 유통사 정산 내역 엑셀파일 validation 로직 추가

BPS-303/마피아 유통사 정산내역 파일 validation

---

src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
src/main/java/com/github/bluekey/repository/track/TrackRepository.java
src/main/resources/sql/data.sql

- 마피아 유통사 정산내역 엑셀파일 데이터를 기반으로 DB에 migration 하는 로직 추가

BPS-304/Mafia excel file migration

---

src/main/java/com/github/bluekey/entity/track/Track.java
src/main/java/com/github/bluekey/entity/transaction/Transaction.java

BPS-324/Transaction table schema

---

src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
src/main/java/com/github/bluekey/processor/validator/DistributorExcelValidator.java
src/main/java/com/github/bluekey/repository/track/TrackRepository.java
src/main/java/com/github/bluekey/repository/transaction/TransactionRepository.java
src/main/java/com/github/bluekey/service/transaction/TransactionService.java
src/main/resources/sql/data.sql

- excel file to DB migration 로직 개선

BPS-325/migration

---

src/main/java/com/github/bluekey/controller/track/TrackController.java
src/main/java/com/github/bluekey/entity/track/Track.java
src/main/java/com/github/bluekey/service/track/TrackService.java

BPS-290/Track 수정 API

---

src/main/java/com/github/bluekey/config/security/SecurityConfig.java

- cors allowOrigin 추가
- reference1

hotfix: cors allowOrigin 추가

---

src/main/java/com/github/bluekey/service/dashboard/DashboardCalculationService.java

- Dashboard에서 사용되는 데이터의 연산식 정의와 예외처리 로직 추가
- docs 추가

BPS-350/Dashboard 데이터 연산식 관리 class 분리

---

src/main/java/com/github/bluekey/entity/track/TrackMember.java
src/main/java/com/github/bluekey/entity/transaction/Transaction.java
src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
src/main/java/com/github/bluekey/repository/transaction/TransactionRepository.java
src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
src/main/java/com/github/bluekey/service/dashboard/LineChartDashBoardService.java
src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java

- Dashboard Service에서 Transaction 데이터들에 대한 가공을 할 시에 trackMember field를 참조하여 groupBy를 하는 로직에 대해서 수정

BPS-359/Transaction trackMember field 참조 로직 제거

---

src/main/java/com/github/bluekey/dto/swagger/request/auth/SignupRequestDto.java
src/main/java/com/github/bluekey/entity/member/MemberRole.java
src/main/java/com/github/bluekey/mail/EmailService.java
src/main/java/com/github/bluekey/repository/member/MemberRepository.java
src/main/java/com/github/bluekey/repository/notification/MemberRequestAuthorityRepository.java
src/main/java/com/github/bluekey/repository/notification/RequestAuthorityRepository.java
src/main/java/com/github/bluekey/service/auth/AuthService.java
src/main/java/com/github/bluekey/service/member/MemberService.java
src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java
src/main/resources/application-local.yml

- 권한 요청 메서드 생성
- 어드민 회원 가입 로직 수정
- reference1

BPS-354/FEAT: 어드민 회원 가입시 권한 요청하도록 구현

---

src/main/java/com/github/bluekey/controller/notification/NotificationController.java
src/main/java/com/github/bluekey/entity/member/Member.java
src/main/java/com/github/bluekey/exception/ErrorCode.java
src/main/java/com/github/bluekey/repository/notification/MemberRequestAuthorityRepository.java
src/main/java/com/github/bluekey/repository/notification/RequestAuthorityRepository.java
src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java

- 권한 요청 승인 API 구현
- reference1

BPS-355/FEAT: 권한 요청 승인 API 구현

---

src/main/java/com/github/bluekey/controller/notification/NotificationController.java
src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java

- 권한 요청에 대해 거절하는 기능을 구현했습니다.
- reference1

BPS-356/FEAT: 권한 요청 거절 API 구현

---

src/main/java/com/github/bluekey/service/dashboard/v2/DashboardCalculationService.java
src/main/java/com/github/bluekey/service/dashboard/v2/DashboardTransactionAdminClient.java
src/main/java/com/github/bluekey/service/dashboard/v2/DashboardTransactionArtistClient.java
src/main/java/com/github/bluekey/service/dashboard/v2/DashboardTransactionFactory.java
src/main/java/com/github/bluekey/service/dashboard/v2/strategy/DashboardTransactionAllStrategy.java
src/main/java/com/github/bluekey/service/dashboard/v2/strategy/DashboardTransactionFilteringStrategy.java
src/main/java/com/github/bluekey/service/dashboard/v2/strategy/DashboardTransactionGroupingStrategy.java
src/main/java/com/github/bluekey/service/dashboard/v2/strategy/DashboardTransactionSortingStrategy.java

- Dashboard transaction data 가공에 대한 전략 interface들과 구현체 구현
- context factory 구현

BPS-367/Dashboard transaction 전략 패턴 개발 건

---

src/main/java/com/github/bluekey/service/dashboard/v2/BarChardDashboardServiceV2.java
src/main/java/com/github/bluekey/service/dashboard/v2/LineChartDashBoardServiceV2.java
src/main/java/com/github/bluekey/service/dashboard/v2/MonthlyTracksDashboardServiceV2.java
src/main/java/com/github/bluekey/service/dashboard/v2/SummaryDashBoardServiceV2.java
src/main/java/com/github/bluekey/service/dashboard/v2/TopTrackDashBoardServiceV2.java
src/main/java/com/github/bluekey/util/DateUtil.java

- Service class 재정의를 위한 versioning된 Service layer 정의
- Date 가공 목적 util성 class 정의

BPS-368/service layer versioning과 DateUtil class 정의

---

src/main/java/com/github/bluekey/service/dashboard/v2/BarChardDashboardServiceV2.java
src/main/java/com/github/bluekey/service/dashboard/v2/BarChartDashboardServiceV2.java
src/main/java/com/github/bluekey/service/dashboard/v2/DashboardTransactionAdminClient.java

- BarChartDashboardServiceV2 class
- DashboardTransactionAdminClient method 기본 로직 구현

BPS-369/DashboardTransactionAdminClient

---

src/main/java/com/github/bluekey/service/auth/AuthService.java

feat: 어드민 회원가입 로직에서 권한 요청 로직 추가

---

src/main/java/com/github/bluekey/controller/notification/NotificationController.java
src/main/java/com/github/bluekey/dto/response/RequestAuthorityPendingStatusResponseDto.java
src/main/java/com/github/bluekey/entity/member/MemberRole.java
src/main/java/com/github/bluekey/entity/notification/RequestStatus.java
src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java

- PENDING status request authority 존재 여부 반환 API 개발

PENDING status request authority 존재 여부 반환 API

---

src/main/java/com/github/bluekey/controller/notification/NotificationController.java
src/main/java/com/github/bluekey/dto/response/RequestAuthorityUpdateResponseDto.java
src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java

- Request Authority 승인과 거절 API Response에 대한 dto class 추가와 반환 로직 추가

Request Authority 승인과 거절 API Response
